var allcategories = {
	"Active Life": {
		"Amateur Sports Teams": "amateursportsteams",
		"Amusement Parks": "amusementparks",
		"Aquariums": "aquariums",
		"Archery": "archery",
		"Bathing Area": "bathing_area",
		"Beaches": "beaches",
		"Bicycle Paths": "bicyclepaths",
		"Bike Rentals": "bikerentals",
		"Boating": "boating",
		"Bowling": "bowling",
		"Climbing": "climbing",
		"Disc Golf": "discgolf",
		"Diving": {
			"Free Diving": "freediving",
			"Scuba Diving": "scuba"
		},
		"Experiences": "experiences",
		"Fishing": "fishing",
		"Fitness & Instruction": {
			"Barre Classes": "barreclasses",
			"Boot Camps": "bootcamps",
			"Dance Studios": "dancestudio",
			"Gyms": "gyms",
			"Martial Arts": "martialarts",
			"Pilates": "pilates",
			"Swimming Lessons/Schools": "swimminglessons",
			"Tai Chi": "taichi",
			"Trainers": "healthtrainers",
			"Yoga": "yoga"
		},
		"Gliding": "gliding",
		"Go Karts": "gokarts",
		"Golf": "golf",
		"Gun/Rifle Ranges": "gun_ranges",
		"Hang Gliding": "hanggliding",
		"Hiking": "hiking",
		"Horse Racing": "horseracing",
		"Horseback Riding": "horsebackriding",
		"Hot Air Balloons": "hot_air_balloons",
		"Indoor Playcentre": "indoor_playcenter",
		"Kids Activities": "kids_activities",
		"Kiteboarding": "kiteboarding",
		"Lakes": "lakes",
		"Lawn Bowling": "lawn_bowling",
		"Leisure Centers": "leisure_centers",
		"Mini Golf": "mini_golf",
		"Mountain Biking": "mountainbiking",
		"Paddleboarding": "paddleboarding",
		"Paintball": "paintball",
		"Parks": {
			"Dog Parks": "dog_parks",
			"Skate Parks": "skate_parks"
		},
		"Playgrounds": "playgrounds",
		"Rafting/Kayaking": "rafting",
		"Recreation Centers": "recreation",
		"Rock Climbing": "rock_climbing",
		"Sailing": "sailing",
		"Skating Rinks": "skatingrinks",
		"Skiing": "skiing",
		"Skydiving": "skydiving",
		"Soccer": "football",
		"Sport Equipment Hire": "sport_equipment_hire",
		"Sports Clubs": "sports_clubs",
		"Summer Camps": "summer_camps",
		"Surfing": "surfing",
		"Swimming Pools": "swimmingpools",
		"Tennis": "tennis",
		"Trampoline Parks": "trampoline",
		"Tubing": "tubing",
		"Zoos": "zoos"
	},
	"Arts & Entertainment": {
		"Arcades": "arcades",
		"Art Galleries": "galleries",
		"Betting Centers": "bettingcenters",
		"Botanical Gardens": "gardens",
		"Casinos": "casinos",
		"Castles": "castles",
		"Choirs": "choirs",
		"Cinema": "movietheaters",
		"Cultural Center": "culturalcenter",
		"Festivals": {
			"Christmas Markets": "xmasmarkets",
			"Fun Fair": "funfair",
			"General Festivals": "generalfestivals",
			"Trade Fairs": "tradefairs"
		},
		"Jazz & Blues": "jazzandblues",
		"Museums": "museums",
		"Music Venues": "musicvenues",
		"Opera & Ballet": "opera",
		"Performing Arts": "theater",
		"Professional Sports Teams": "sportsteams",
		"Psychics & Astrologers": "psychic_astrology",
		"Social Clubs": "social_clubs",
		"Stadiums & Arenas": "stadiumsarenas",
		"Street Art": "streetart",
		"Tablao Flamenco": "tablaoflamenco",
		"Ticket Sales": "ticketsales",
		"Wineries": "wineries"
	},
	"Automotive": {
		"Auto Detailing": "auto_detailing",
		"Auto Glass Services": "autoglass",
		"Auto Parts & Supplies": "autopartssupplies",
		"Auto Repair": "autorepair",
		"Boat Dealers": "boatdealers",
		"Body Shops": "bodyshops",
		"Car Dealers": "car_dealers",
		"Car Stereo Installation": "stereo_installation",
		"Car Wash": "carwash",
		"Gas & Service Stations": "servicestations",
		"Motorcycle Dealers": "motorcycledealers",
		"Motorcycle Repair": "motorcyclerepair",
		"Oil Change Stations": "oilchange",
		"Parking": "parking",
		"RV Dealers": "rv_dealers",
		"Smog Check Stations": "smog_check_stations",
		"Tires": "tires",
		"Towing": "towing",
		"Truck Rental": "truck_rental",
		"Windshield Installation & Repair": "windshieldinstallrepair"
	},
	"Beauty and Spas": {
		"Barbers": "barbers",
		"Cosmetics & Beauty Supply": "cosmetics",
		"Day Spas": "spas",
		"Eyelash Service": "eyelashservice",
		"Hair Extensions": "hair_extensions",
		"Hair Removal": {
			"Laser Hair Removal": "laser_hair_removal"
		},
		"Hair Salons": {
			"Hair Extensions": "hair_extensions",
			"Hair Stylists": "hairstylists",
			"Men's Hair Salons": "menshair"
		},
		"Makeup Artists": "makeupartists",
		"Massage": "massage",
		"Medical Spas": "medicalspa",
		"Nail Salons": "othersalons",
		"Perfume": "perfume",
		"Piercing": "piercing",
		"Rolfing": "rolfing",
		"Skin Care": "skincare",
		"Tanning": "tanning",
		"Tattoo": "tattoo"
	},
	"Bicycles": {
		"Bike Associations": "bikeassociations",
		"Bike Repair": "bikerepair",
		"Bike Shop": "bikeshop",
		"Special Bikes": "specialbikes"
	},
	"Education": {
		"Adult Education": "adultedu",
		"College Counseling": "collegecounseling",
		"Colleges & Universities": "collegeuniv",
		"Educational Services": "educationservices",
		"Elementary Schools": "elementaryschools",
		"Middle Schools & High Schools": "highschools",
		"Preschools": "preschools",
		"Private Schools": "privateschools",
		"Private Tutors": "privatetutors",
		"Religious Schools": "religiousschools",
		"Special Education": "specialed",
		"Specialty Schools": {
			"Art Schools": "artschools",
			"CPR Classes": "cprclasses",
			"Circus Schools": "circusschools",
			"Cooking Schools": "cookingschools",
			"Cosmetology Schools": "cosmetology_schools",
			"Dance Schools": "dance_schools",
			"Driving Schools": "driving_schools",
			"Flight Instruction": "flightinstruction",
			"Language Schools": "language_schools",
			"Massage Schools": "massage_schools",
			"Swimming Lessons/Schools": "swimminglessons",
			"Vocational and Technical School": "vocation"
		},
		"Test Preparation": "testprep",
		"Tutoring Centers": "tutoring"
	},
	"Event Planning & Services": {
		"Bartenders": "bartenders",
		"Boat Charters": "boatcharters",
		"Cards & Stationery": "stationery",
		"Caterers": "catering",
		"Clowns": "clowns",
		"DJs": "djs",
		"Hotels": "hotels",
		"Magicians": "magicians",
		"Musicians": "musicians",
		"Officiants": "officiants",
		"Party & Event Planning": "eventplanning",
		"Party Bus Rentals": "partybusrentals",
		"Party Equipment Rentals": "partyequipmentrentals",
		"Party Supplies": "partysupplies",
		"Personal Chefs": "personalchefs",
		"Photographers": {
			"Event Photography": "eventphotography",
			"Session Photography": "sessionphotography"
		},
		"Venues & Event Spaces": "venues",
		"Videographers": "videographers",
		"Wedding Planning": "wedding_planning"
	},
	"Financial Services": {
		"Banks & Credit Unions": "banks",
		"Check Cashing/Pay-day Loans": "paydayloans",
		"Financial Advising": "financialadvising",
		"Insurance": "insurance",
		"Investing": "investing",
		"Tax Services": "taxservices"
	},
	"Food": {
		"Bagels": "bagels",
		"Bakeries": "bakeries",
		"Beer, Wine & Spirits": "beer_and_wine",
		"Beverage Store": "beverage_stores",
		"Breweries": "breweries",
		"Bubble Tea": "bubbletea",
		"Butcher": "butcher",
		"CSA": "csa",
		"Churros": "churros",
		"Coffee & Tea": "coffee",
		"Convenience Stores": "convenience",
		"Delicatessen": "delicatessen",
		"Desserts": "desserts",
		"Do-It-Yourself Food": "diyfood",
		"Donairs": "donairs",
		"Donuts": "donuts",
		"Ethic Grocery": "ethicgrocery",
		"Farmers Market": "farmersmarket",
		"Food Delivery Services": "fooddeliveryservices",
		"Food Trucks": "foodtrucks",
		"Friterie": "friterie",
		"Gelato": "gelato",
		"Grocery": "grocery",
		"Ice Cream & Frozen Yogurt": "icecream",
		"Internet Cafes": "internetcafe",
		"Juice Bars & Smoothies": "juicebars",
		"Kiosk": "kiosk",
		"Organic Stores": "organic_stores",
		"Parent Cafes": "eltern_cafes",
		"Patisserie/Cake Shop": "cakeshop",
		"Shaved Ice": "shavedice",
		"Specialty Food": {
			"Candy Stores": "candy",
			"Cheese Shops": "cheese",
			"Chocolatiers and Shops": "chocolate",
			"Ethnic Food": "ethnicmarkets",
			"Fruits & Veggies": "markets",
			"Health Markets": "healthmarkets",
			"Herbs and Spices": "herbsandspices",
			"Meat Shops": "meats",
			"Seafood Markets": "seafoodmarkets"
		},
		"Street Vendors": "streetvendors",
		"Tea Rooms": "tea",
		"Wineries": "wineries"
	},
	"Health and Medical": {
		"Acupuncture": "acupuncture",
		"Cannabis Clinics": "cannabis_clinics",
		"Chiropractors": "chiropractors",
		"Counseling & Mental Health": "c_and_mh",
		"Dentists": {
			"Cosmetic Dentists": "cosmeticdentists",
			"Endodontists": "endodontists",
			"General Dentistry": "generaldentistry",
			"Oral Surgeons": "oralsurgeons",
			"Orthodontists": "orthodontists",
			"Pediatric Dentists": "pediatric_dentists",
			"Periodontists": "periodontists"
		},
		"Diagnostic Services": {
			"Diagnostic Imaging": "diagnosticimaging",
			"Laboratory Testing": "laboratorytesting"
		},
		"Doctors": {
			"Allergists": "allergist",
			"Anesthesiologists": "anesthesiologists",
			"Audiologist": "audiologist",
			"Cardiologists": "cardiology",
			"Cosmetic Surgeons": "cosmeticsurgeons",
			"Dermatologists": "dermatology",
			"Ear Nose & Throat": "earnosethroat",
			"Family Practice": "familydr",
			"Fertility": "fertility",
			"Gastroenterologist": "gastroenterologist",
			"Gerontologists": "gerontologist",
			"Internal Medicine": "internalmed",
			"Naturopathic/Holistic": "naturopathic",
			"Neurologist": "neurologist",
			"Obstetricians and Gynecologists": "obgyn",
			"Oncologist": "oncologist",
			"Ophthalmologists": "opthamalogists",
			"Orthopedists": "orthopedists",
			"Osteopathic Physicians": "osteopathicphysicians",
			"Pediatricians": "pediatricians",
			"Podiatrists": "podiatrists",
			"Proctologists": "proctologist",
			"Psychiatrists": "psychiatrists",
			"Pulmonologist": "pulmonologist",
			"Sports Medicine": "sportsmed",
			"Surgeons": "surgeons",
			"Tattoo Removal": "tattooremoval"
		},
		"Hearing Aid Providers": "hearingaidproviders",
		"Hearing Aids": "hearing_aids",
		"Home Health Care": "homehealthcare",
		"Hospice": "hospice",
		"Hospitals": "hospitals",
		"Lactation Services": "lactationservices",
		"Laser Eye Surgery/Lasik": "laserlasikeyes",
		"Massage Therapy": "massage_therapy",
		"Medical Centers": {
			"Bulk Billing": "bulkbilling",
			"Osteopaths": "osteopaths",
			"Walk-in Clinics": "walkinclinics"
		},
		"Medical Spas": "medicalspa",
		"Medical Transportation": "medicaltransportation",
		"Midwives": "midwives",
		"Nutritionists": "nutritionists",
		"Occupational Therapy": "occupationaltherapy",
		"Optometrists": "optometrists",
		"Pharmacy": "pharmacy",
		"Physical Therapy": "physicaltherapy",
		"Reflexology": "reflexology",
		"Rehabilitation Center": "rehabilitation_center",
		"Retirement Homes": "retirement_homes",
		"Saunas": "saunas",
		"Speech Therapists": "speech_therapists",
		"Traditional Chinese Medicine": "tcm",
		"Urgent Care": "urgent_care",
		"Weight Loss Centers": "weightlosscenters"
	},
	"Home Services": {
		"Building Supplies": "buildingsupplies",
		"Carpenters": "carpenters",
		"Carpet Installation": "carpetinstallation",
		"Carpeting": "carpeting",
		"Contractors": "contractors",
		"Electricians": "electricians",
		"Flooring": "flooring",
		"Garage Door Services": "garage_door_services",
		"Gardeners": "gardeners",
		"Handyman": "handyman",
		"Heating & Air Conditioning/HVAC": "hvac",
		"Home Cleaning": "homecleaning",
		"Home Inspectors": "home_inspectors",
		"Home Organization": "home_organization",
		"Home Theatre Installation": "hometheatreinstallation",
		"Interior Design": "interiordesign",
		"Internet Service Providers": "isps",
		"Keys & Locksmiths": "locksmiths",
		"Landscape Architects": "landscapearchitects",
		"Landscaping": "landscaping",
		"Lighting Fixtures & Equipment": "lighting",
		"Masonry/Concrete": "masonry_concrete",
		"Movers": "movers",
		"Painters": "painters",
		"Plumbing": "plumbing",
		"Pool Cleaners": "poolcleaners",
		"Real Estate": {
			"Apartments": "apartments",
			"Commercial Real Estate": "commercialrealestate",
			"Home Staging": "homestaging",
			"Mortgage Brokers": "mortgagebrokers",
			"Property Management": "propertymgmt",
			"Real Estate Agents": "realestateagents",
			"Real Estate Services": "realestatesvcs",
			"Shared Office Spaces": "sharedofficespaces",
			"University Housing": "university_housing"
		},
		"Roofing": "roofing",
		"Security Systems": "securitysystems",
		"Shades & Blinds": "blinds",
		"Solar Installation": "solarinstallation",
		"Television Service Providers": "televisionserviceproviders",
		"Tree Services": "treeservices",
		"Utilities": "utilities",
		"Window Washing": "windowwashing",
		"Windows Installation": "windowsinstallation"
	},
	"Hotels & Travel": {
		"Airports": "airports",
		"Bed & Breakfast": "bedbreakfast",
		"Campgrounds": "campgrounds",
		"Car Rental": "carrental",
		"Guest Houses": "guesthouses",
		"Hostels": "hostels",
		"Hotels": "hotels",
		"Motorcycle Rental": "motorcycle_rental",
		"RV Rental": "rvrental",
		"Resorts": "resorts",
		"Ski Resorts": "skiresorts",
		"Tours": "tours",
		"Train Stations": "trainstations",
		"Transportation": {
			"Airlines": "airlines",
			"Airport Shuttles": "airport_shuttles",
			"Ferries": "ferries",
			"Limos": "limos",
			"Public Transportation": "publictransport",
			"Taxis": "taxis"
		},
		"Water Taxis": "watertaxis",
		"Travel Services": "travelservices",
		"Vacation Rental Agents": "vacationrentalagents",
		"Vacation Rentals": "vacation_rentals"
	},
	"Local Flavor": "localflavor",
	"Local Services": {
		"Appliances & Repair": "homeappliancerepair",
		"Bail Bondsmen": "bailbondsmen",
		"Bike Repair/Maintenance": "bike_repair_maintenance",
		"Carpet Cleaning": "carpet_cleaning",
		"Child Care & Day Care": "childcare",
		"Community Service/Non-Profit": "nonprofit",
		"Couriers & Delivery Services": "couriers",
		"Dry Cleaning & Laundry": "drycleaninglaundry",
		"Electronics Repair": "electronicsrepair",
		"Funeral Services & Cemeteries": "funeralservices",
		"Furniture Reupholstery": "reupholstery",
		"IT Services & Computer Repair": {
			"Data Recovery": "datarecovery",
			"Mobile Phone Repair": "mobilephonerepair"
		},
		"Junk Removal and Hauling": "junkremovalandhauling",
		"Notaries": "notaries",
		"Pest Control": "pest_control",
		"Printing Services": "copyshops",
		"Record Labels": "record_labels",
		"Recording & Rehearsal Studios": "recording_studios",
		"Recycling Center": "recyclingcenter",
		"Screen Printing": "screenprinting",
		"Screen Printing/T-Shirt Printing": "screen_printing_tshirt_printing",
		"Self Storage": "selfstorage",
		"Sewing & Alterations": "sewingalterations",
		"Shipping Centers": "shipping_centers",
		"Shoe Repair": "shoerepair",
		"Snow Removal": "snowremoval",
		"Watch Repair": "watch_repair",
		"Youth Club": "youth_club"
	},
	"Mass Media": {
		"Print Media": "printmedia",
		"Radio Stations": "radiostations",
		"Television Stations": "televisionstations"
	},
	"Nightlife": {
		"Adult Entertainment": "adultentertainment",
		"Bars": {
			"Beach Bars": "beachbars",
			"Beer Bar": "beerbar",
			"Champagne Bars": "champagne_bars",
			"Cocktail Bars": "cocktailbars",
			"Dive Bars": "divebars",
			"Gay Bars": "gaybars",
			"Hookah Bars": "hookah_bars",
			"Hotel bar": "hotel_bar",
			"Irish Pub": "irish_pubs",
			"Lounges": "lounges",
			"Pubs": "pubs",
			"Sports Bars": "sportsbars",
			"Wine Bars": "wine_bars"
		},
		"Beer Gardens": "beergardens",
		"Coffeeshops": "coffeeshops",
		"Comedy Clubs": "comedyclubs",
		"Country Dance Halls": "countrydancehalls",
		"Dance Clubs": "danceclubs",
		"Dance Restaurants": "dancerestaurants",
		"Jazz & Blues": "jazzandblues",
		"Karaoke": "karaoke",
		"Music Venues": "musicvenues",
		"Piano Bars": "pianobars",
		"Pool Halls": "poolhalls"
	},
	"Pets": {
		"Animal Shelters": "animalshelters",
		"Horse Boarding": "horse_boarding",
		"Pet Services": {
			"Dog Walkers": "dogwalkers",
			"Pet Boarding/Pet Sitting": "pet_sitting",
			"Pet Groomers": "groomer",
			"Pet Training": "pet_training"
		},
		"Pet Stores": "petstore",
		"Veterinarians": "vet"
	},
	"Professional Services": {
		"Accountants": "accountants",
		"Advertising": "advertising",
		"Architects": "architects",
		"Boat Repair": "boatrepair",
		"Career Counseling": "careercounseling",
		"Employment Agencies": "employmentagencies",
		"Graphic Design": "graphicdesign",
		"Internet Service Providers": "isps",
		"Lawyers": {
			"Bankruptcy Law": "bankruptcy",
			"Criminal Defense Law": "criminaldefense",
			"Divorce and Family Law": "divorce",
			"Employment Law": "employmentlawyers",
			"Estate Planning Law": "estateplanning",
			"General Litigation": "general_litigation",
			"Immigration Law": "immigrationlawyers",
			"Personal Injury Law": "personal_injury",
			"Real Estate Law": "realestatelawyers"
		},
		"Life Coach": "lifecoach",
		"Marketing": "marketing",
		"Matchmakers": "matchmakers",
		"Office Cleaning": "officecleaning",
		"Personal Assistants": "personalassistants",
		"Private Investigation": "privateinvestigation",
		"Public Relations": "publicrelations",
		"Security Services": "security",
		"Talent Agencies": "talentagencies",
		"Translation Services": "translationservices",
		"Video/Film Production": "videofilmproductions",
		"Web Design": "web_design"
	},
	"Public Services & Government": {
		"Authorized Postal Representative": "authorized_postal_representative",
		"Courthouses": "courthouses",
		"Departments of Motor Vehicles": "departmentsofmotorvehicles",
		"Embassy": "embassy",
		"Landmarks & Historical Buildings": "landmarks",
		"Libraries": "libraries",
		"Police Departments": "policedepartments",
		"Post Offices": "postoffices",
		"Registry Office": "registry_office",
		"Tax Office": "taxoffice"
	},
	"Real Estate": {
		"Apartments": "apartments",
		"Commercial Real Estate": "commercialrealestate",
		"Home Staging": "homestaging",
		"Mortgage Brokers": "mortgagebrokers",
		"Property Management": "propertymgmt",
		"Real Estate Agents": "realestateagents",
		"Real Estate Services": "realestatesvcs",
		"Shared Office Spaces": "sharedofficespaces",
		"University Housing": "university_housing"
	},
	"Religious Organizations": {
		"Buddhist Temples": "buddhist_temples",
		"Churches": "churches",
		"Hindu Temples": "hindu_temples",
		"Mosques": "mosques",
		"Synagogues": "synagogues"
	},
	"Restaurants": {
		"Afghan": "afghani",
		"African": {
			"Senegalese": "senegalese",
			"South African": "southafrican"
		},
		"American (New)": "newamerican",
		"American (Traditional)": "tradamerican",
		"Arabian": "arabian",
		"Argentine": "argentine",
		"Asian Fusion": "asianfusion",
		"Asturian": "asturian",
		"Australian": "australian",
		"Austrian": "austrian",
		"Bangladeshi": "bangladeshi",
		"Barbeque": "bbq",
		"Basque": "basque",
		"Bavarian": "bavarian",
		"Beer Garden": "beergarden",
		"Beer Hall": "beerhall",
		"Belgian": "belgian",
		"Bistros": "bistros",
		"Brasseries": "brasseries",
		"Brazilian": "brazilian",
		"Breakfast & Brunch": "breakfast_brunch",
		"British": "british",
		"Buffets": "buffets",
		"Bulgarian": "bulgarian",
		"Burgers": "burgers",
		"Burmese": "burmese",
		"Cafes": "cafes",
		"Cafeteria": "cafeteria",
		"Cajun/Creole": "cajun",
		"Cambodian": "cambodian",
		"Canadian (New)": "newcanadian",
		"Canteen": "canteen",
		"Caribbean": {
			"Dominican": "dominican",
			"Haitian": "haitian",
			"Puerto Rican": "puertorican",
			"Trinidadian": "trinidadian"
		},
		"Catalan": "catalan",
		"Chech": "chech",
		"Cheesesteaks": "cheesesteaks",
		"Chicken Shop": "chickenshop",
		"Chicken Wings": "chicken_wings",
		"Chinese": {
			"Cantonese": "cantonese",
			"Dim Sum": "dimsum",
			"Fuzhou": "fuzhou",
			"Hakka": "hakka",
			"Henghwa": "henghwa",
			"Hokkien": "hokkien",
			"Shanghainese": "shanghainese",
			"Szechuan": "szechuan",
			"Teochew": "teochew"
		},
		"Comfort Food": "comfortfood",
		"Corsican": "corsican",
		"Creperies": "creperies",
		"Cuban": "cuban",
		"Curry Sausage": "currysausage",
		"Cypriot": "cypriot",
		"Czech/Slovakian": "czechslovakian",
		"Danish": "danish",
		"Delis": "delis",
		"Diners": "diners",
		"Eastern European": "eastern_european",
		"Ethiopian": "ethiopian",
		"Fast Food": "hotdogs",
		"Filipino": "filipino",
		"Fish & Chips": "fishnchips",
		"Fondue": "fondue",
		"Food Court": "food_court",
		"Food Stands": "foodstands",
		"French": "french",
		"French Southwest": "sud_ouest",
		"Galician": "galician",
		"Gastropubs": "gastropubs",
		"Georgian": "georgian",
		"German": "german",
		"Gluten-Free": "gluten_free",
		"Greek": "greek",
		"Halal": "halal",
		"Hawaiian": "hawaiian",
		"Himalayan/Nepalese": "himalayan",
		"Hot Dogs": "hotdog",
		"Hot Pot": "hotpot",
		"Hungarian": "hungarian",
		"Iberian": "iberian",
		"Indian": "indpak",
		"Indonesian": "indonesian",
		"International": "international",
		"Irish": "irish",
		"Island Pub": "island_pub",
		"Israeli": "israeli",
		"Italian": {
			"Altoatesine": "altoatesine",
			"Apulian": "apulian",
			"Calabrian": "calabrian",
			"Cucina campana": "cucinacampana",
			"Emilian": "emilian",
			"Friulan": "friulan",
			"Ligurian": "ligurian",
			"Lumbard": "lumbard",
			"Roman": "roman",
			"Sardinian": "sardinian",
			"Sicilian": "sicilian",
			"Tuscan": "tuscan",
			"Venetian": "venetian"
		},
		"Japanese": {
			"Izakaya": "izakaya",
			"Teppanyaki": "teppanyaki"
		},
		"Jewish": "jewish",
		"Kebab": "kebab",
		"Korean": "korean",
		"Kosher": "kosher",
		"Kurdish": "kurdish",
		"Laos": "laos",
		"Laotian": "laotian",
		"Latin American": {
			"Colombian": "colombian",
			"Salvadoran": "salvadoran",
			"Venezuelan": "venezuelan"
		},
		"Live/Raw Food": "raw_food",
		"Lyonnais": "lyonnais",
		"Malaysian": {
			"Mamak": "mamak",
			"Nyonya": "nyonya"
		},
		"Mediterranean": "mediterranean",
		"Mexican": "mexican",
		"Middle Eastern": {
			"Egyptian": "egyptian",
			"Lebanese": "lebanese"
		},
		"Milk Bars": "milkbars",
		"Modern Australian": "modern_australian",
		"Modern European": "modern_european",
		"Mongolian": "mongolian",
		"Moroccan": "moroccan",
		"Night Food": "nightfood",
		"Open Sandwiches": "opensandwiches",
		"Oriental": "oriental",
		"Pakistani": "pakistani",
		"Parent Cafes": "eltern_cafes",
		"Parma": "parma",
		"Persian/Iranian": "persian",
		"Peruvian": "peruvian",
		"Pizza": "pizza",
		"Polish": {
			"Pierogis": "pierogis"
		},
		"Portuguese": "portuguese",
		"Potatoes": "potatoes",
		"Poutineries": "poutineries",
		"Pub Food": "pubfood",
		"Romanian": "romanian",
		"Rotisserie Chicken": "rotisserie_chicken",
		"Rumanian": "rumanian",
		"Russian": "russian",
		"Salad": "salad",
		"Sandwiches": "sandwiches",
		"Scandinavian": "scandinavian",
		"Scottish": "scottish",
		"Seafood": "seafood",
		"Serbo Croatian": "serbocroatian",
		"Signature Cuisine": "signature_cuisine",
		"Singaporean": "singaporean",
		"Soul Food": "soulfood",
		"Soup": "soup",
		"Southern": "southern",
		"Spanish": {
			"Arroceria / Paella": "arroceria_paella"
		},
		"Steakhouses": "steak",
		"Sushi Bars": "sushi",
		"Swabian": "swabian",
		"Swedish": "swedish",
		"Swiss Food": "swissfood",
		"Tabernas": "tabernas",
		"Taiwanese": "taiwanese",
		"Tapas Bars": "tapas",
		"Tapas/Small Plates": "tapasmallplates",
		"Tex-Mex": "tex-mex",
		"Thai": "thai",
		"Traditional Norwegian": "norwegian",
		"Traditional Swedish": "traditional_swedish",
		"Turkish": "turkish",
		"Ukrainian": "ukrainian",
		"Vegan": "vegan",
		"Vegetarian": "vegetarian",
		"Venison": "venison",
		"Vietnamese": "vietnamese",
		"Wok": "wok",
		"Wraps": "wraps",
		"Yugoslav": "yugoslav"
	},
	"Shopping": {
		"Adult": "adult",
		"Antiques": "antiques",
		"Art Galleries": "galleries",
		"Arts & Crafts": {
			"Art Supplies": "artsupplies",
			"Cards & Stationery": "stationery",
			"Costumes": "costumes",
			"Embroidery & Crochet": "embroideryandcrochet",
			"Fabric Stores": "fabricstores",
			"Framing": "framing"
		},
		"Auction Houses": "auctionhouses",
		"Baby Gear & Furniture": "baby_gear",
		"Bespoke Clothing": "bespoke",
		"Books, Mags, Music and Video": {
			"Bookstores": "bookstores",
			"Comic Books": "comicbooks",
			"Music & DVDs": "musicvideo",
			"Newspapers & Magazines": "mags",
			"Videos and Video Game Rental": "videoandgames",
			"Vinyl Records": "vinyl_records"
		},
		"Bridal": "bridal",
		"Chinese Bazaar": "chinesebazaar",
		"Computers": "computers",
		"Concept Shops": "concept_shops",
		"Cosmetics & Beauty Supply": "cosmetics",
		"Department Stores": "deptstores",
		"Discount Store": "discountstore",
		"Drugstores": "drugstores",
		"Electronics": "electronics",
		"Eyewear & Opticians": "opticians",
		"Fashion": {
			"Accessories": "accessories",
			"Children's Clothing": "childcloth",
			"Department Stores": "deptstores",
			"Formal Wear": "formalwear",
			"Hats": "hats",
			"Leather Goods": "leather",
			"Lingerie": "lingerie",
			"Maternity Wear": "maternity",
			"Men's Clothing": "menscloth",
			"Plus Size Fashion": "plus_size_fashion",
			"Shoe Stores": "shoes",
			"Sleepwear": "sleepwear",
			"Sports Wear": "sportswear",
			"Surf Shop": "surfshop",
			"Swimwear": "swimwear",
			"Used, Vintage & Consignment": "vintage",
			"Women's Clothing": "womenscloth"
		},
		"Fireworks": "fireworks",
		"Flea Markets": "fleamarkets",
		"Flowers & Gifts": {
			"Cards & Stationery": "stationery",
			"Florists": "florists",
			"Flowers": "flowersonly",
			"Gift Shops": "giftshops"
		},
		"Guns & Ammo": "guns_and_ammo",
		"Hobby Shops": "hobbyshops",
		"Home & Garden": {
			"Appliances": "appliances",
			"Furniture Stores": "furniture",
			"Hardware Stores": "hardware",
			"Home Decor": "homedecor",
			"Hot Tub and Pool": "hottubandpool",
			"Kitchen & Bath": "kitchenandbath",
			"Linens": "linens",
			"Mattresses": "mattresses",
			"Nurseries & Gardening": "gardening",
			"Tableware": "tableware"
		},
		"Jewelry": "jewelry",
		"Kiosk": "kiosk",
		"Knitting Supplies": "knittingsupplies",
		"Luggage": "luggage",
		"Market Stalls": "marketstalls",
		"Mobile Phones": "mobilephones",
		"Musical Instruments & Teachers": "musicalinstrumentsandteachers",
		"Office Equipment": "officeequipment",
		"Outlet Stores": "outlet_stores",
		"Pawn Shops": "pawn",
		"Perfume": "perfume",
		"Personal Shopping": "personal_shopping",
		"Photography Stores & Services": "photographystores",
		"Scandinavian Design": "scandinaviandesign",
		"Shopping Centers": "shoppingcenters",
		"Souvenir Shops": "souvenirs",
		"Spiritual Shop": "spiritual_shop",
		"Sporting Goods": {
			"Bikes": "bikes",
			"Golf Equipment": "golfequipment",
			"Outdoor Gear": "outdoorgear",
			"Sports Wear": "sportswear"
		},
		"Thrift Stores": "thrift_stores",
		"Tickets": "tickets",
		"Tobacco Shops": "tobaccoshops",
		"Toy Stores": "toys",
		"Uniforms": "uniforms",
		"Used Bookstore": "usedbooks",
		"Watches": "watches",
		"Wholesale Stores": "wholesale_stores",
		"Wigs": "wigs"
	}
}